project:
  type: book
  output-dir: docs
  
book:
  title: "CASA0023 Learning Diary"
  author: "Zhaowei Cui"
  date: "2024/2/10"
  chapters:
    - index.qmd
    - week1.qmd
    - week2.qmd
    - week3.qmd
    - week4.qmd
    - week6.qmd
    - week7.qmd
    - week8.qmd
    - week9.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

