project:
  type: book
  output-dir: docs
  
book:
  title: "CASA0023 Learning Diary"
  author: "Zhaowei Cui"
  date: "2024/2/10"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

